name: Update Deployment

on:
  repository_dispatch:
    types: [deploy]

permissions:
  contents: write

jobs:
  update-manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update deployment image
        run: |
          IMAGE="${{ github.event.client_payload.image }}"

          sed -i "s|image:.*|image: ${IMAGE}|g" manifests/deployment.yaml

      - name: Commit and push
        run: |
          IMAGE="${{ github.event.client_payload.image }}"
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add manifests/deployment.yaml

          git commit -m "Update deployment image to ${IMAGE}" || echo "No changes to commit"

          git push origin main